[package]
name = "chart_rs"
version = "0.2.0"
edition = "2021"
authors = ["Floris floris@xylex.ai"]
description = "Blazingly fast charting library"
license = "MIT"
readme = "README.md"

[dependencies]
anyhow = "1.0.82"
image = "0.25.1"
